name: Dario Vignali
favicon: null
layout_spectrum: 0.75145
typography_spectrum: 0.69225
title: Dario Vignali
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b2b2b'
    - '#a6a7ab'
    - '#656766'
    - '#9b450e'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.4947516662068665
purpose: []
