name: Dario Vignali
favicon: null
layout_spectrum: 0
typography_spectrum: 0.42443
title: Dario Vignali
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#b7b7b7'
    - '#585858'
    - '#828282'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
