name: Dario Vignali
favicon: null
layout_spectrum: 0.5458841521758586
typography_spectrum: 0.8502532399725169
title: Dario Vignali
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b2b2b'
    - '#a6a7ab'
    - '#656766'
    - '#9b450e'
  brandStrength: 0.8125
  lightness: 0.9529012395069003
  saturation: 0.872892317827791
  rhythmicContrast: 0.4947516662068665
purpose: []
